DXM-180 Updated the instruction and the screenshots with new UI.
qualtrics/qualtrics-digital-ios-sdk pull request #3
Opened 2023-03-02 17:22 UTC by Sileo1024

Closes [DXM-180](https://qualtrics.atlassian.net/browse/DXM-180 )

2023-03-03 12:41 UTC, hardkov commented
lgmt

2023-03-06 18:11 UTC, rbalog-qualtrics requested changes

2023-03-06 18:11 UTC, rbalog-qualtrics commented on README.md
> +Add a dependency on qualtrics-digital-ios-sdk to your ios application through Xcode by following these steps:
```suggestion
Add a dependency on qualtrics-digital-ios-sdk to your iOS application through Xcode with the following steps:
```

2023-03-06 18:11 UTC, rbalog-qualtrics commented on README.md
> +#### 5. Make sure the package is added (for example for application `QualtricsSDKSwiftUI` it should appear on the left menu in files structures, and look as follows):
```suggestion
#### 5. Verify that the package has been added to your Project Navigator in Xcode, under `Package Dependencies` (In this example, it is directly under our example app `QualtricsSDKSwiftUI`):
```

2023-03-06 18:18 UTC, rbalog-qualtrics approved these changes

2023-03-06 18:18 UTC, merged